### ISSUE TITLE
Request for Help with Editing/Replacing Text in Paragraphs

### ISSUE THREAD

**Issue by saithan-ph** [fumiama/go-docx#43]
Thank you for your work.

I need to edit or replace text in paragraphs from .docx template, but I cannot find an example. Could you please provide guidance or an example on how to accomplish this?

"{{NAME}}": "John Doe",
"{{DATE}}": "October 15, 2024",

Thank you!

**Comment by fumiama** [comment]
> This lib is not template-oriented, so it is easier to build a docx file from scratch than replace placeholder in an existing docx file.

If you really need to do it, please note that this lib will drop all properties that it doesn't know when parsing. You can perform a parse-and-write cycle to check whether all formats from the original file have been kept in the output file or not. 

If the changes are acceptable, the next step you should do is to `merge` all `<w:t>` tags with the same properties together because in OpenXML, `{{NAME}}` may be stored separately like `{{`, `NAME` and `}}` even they are all in the same line. You can do this by calling method like `para.MergeText(docx.MergeSamePropRuns)`, but the result may not always meet your requirement, so you need to adjust them. See more detail at `structtext_test.go`.

Finally, you are able to replace the text using regex, by ranging every paras in the docx body.
